# GoReleaser configuration for ghspector
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/ghspector/main.go
    binary: ghspector
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/joangrigorov/ghspector
    maintainer: Yoan-Alexander Grigorov
    description: "Sleek, terminal-native TUI for browsing, monitoring, and debugging GitHub Actions workflows."
    license: MIT
    formats:
      - deb
      - rpm
      - apk

archives:
  - formats:
      - tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
